/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemoncardgame;


/**
 *
 * @author askilic
 */
public class GameInstruction extends javax.swing.JFrame {

    /**
     * Creates new form gameInstruction
     */
    public GameInstruction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPics1 = new javax.swing.JLabel();
        cardPics2 = new javax.swing.JLabel();
        howToPlay = new javax.swing.JLabel();
        howToPlay1 = new javax.swing.JLabel();
        howToPlay2 = new javax.swing.JLabel();
        howToPlay3 = new javax.swing.JLabel();
        howToPlay4 = new javax.swing.JLabel();
        instruction = new javax.swing.JLabel();
        instruction1 = new javax.swing.JLabel();
        instruction2 = new javax.swing.JLabel();
        instruction3 = new javax.swing.JLabel();
        backToMainMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(450, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardPics1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/charmanderPicsInGameInstruction.png"))); // NOI18N
        getContentPane().add(cardPics1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 250));

        cardPics2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pikachuPicsInGameInstruction.png"))); // NOI18N
        getContentPane().add(cardPics2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 180, 250));

        howToPlay.setForeground(java.awt.Color.red);
        howToPlay.setText("How to Play");
        getContentPane().add(howToPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        howToPlay1.setText("1-) Toplam 10 kart vardır oyunun başında 3' er 3'er kart dağıtılır");
        getContentPane().add(howToPlay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 450, 20));

        howToPlay2.setText("2-) Dağıtılan kartlardan seçilen kart rakibin seçtiği ile karşılaştırılır");
        getContentPane().add(howToPlay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 460, -1));

        howToPlay3.setText("3-) Hasar puanı daha yüksek olan kart turu kazanır ve 5 puan alır");
        getContentPane().add(howToPlay3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 460, -1));

        howToPlay4.setText("4-) 10 kart bitince puanlar hesaplanır ve kazan mesaj ile gösterilir");
        getContentPane().add(howToPlay4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 460, -1));

        instruction.setForeground(java.awt.Color.red);
        instruction.setText("Instruction");
        getContentPane().add(instruction, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 80, -1));

        instruction1.setText("1-) Bilgisayar ve kullanıcı için kart dağıtımı rastgeledir ");
        getContentPane().add(instruction1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 460, -1));

        instruction2.setText("2-) Kart seçimde ise kullanıcı kendi seçer ,bilgisayar ise rastgeledir");
        getContentPane().add(instruction2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 460, -1));

        instruction3.setText("3-) Seçim işlemi click(mouse ile tıklama) ile yapılır");
        getContentPane().add(instruction3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 470, -1));

        backToMainMenu.setText("Back to Main Menu");
        backToMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainMenuActionPerformed(evt);
            }
        });
        getContentPane().add(backToMainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMainMenuActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_backToMainMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameInstruction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameInstruction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameInstruction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameInstruction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameInstruction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMainMenu;
    private javax.swing.JLabel cardPics1;
    private javax.swing.JLabel cardPics2;
    private javax.swing.JLabel howToPlay;
    private javax.swing.JLabel howToPlay1;
    private javax.swing.JLabel howToPlay2;
    private javax.swing.JLabel howToPlay3;
    private javax.swing.JLabel howToPlay4;
    private javax.swing.JLabel instruction;
    private javax.swing.JLabel instruction1;
    private javax.swing.JLabel instruction2;
    private javax.swing.JLabel instruction3;
    // End of variables declaration//GEN-END:variables
}
